#!/bin/bash
## Description: Run building sequences in the web container
## Usage: build
## Example: "ddev build"
## Flags: [{"Name":"clearcache","Usage":"Clears the composer cache before installing"}]
source "$(dirname "$0")/common.sh"

CLEAR_CACHE=0
while true
do
    case $1 in
        --clearcache)
            CLEAR_CACHE=1
            shift
            break
            ;;
        --)
            shift
            break
            ;;
    esac
done

log "\e[36m--------- Running build ---------\e[39m"

cd "${PWD}" || exit 1;

if [[ CLEAR_CACHE -eq 1 ]]; then
    log "Clearing Composer cache"
    composer clearcache --quiet
    log "Composer cache cleared"
fi

log "Installing composer dependencies (with development dependencies)."
composer install --no-interaction --no-progress --apcu-autoloader || exit 1;
log "Composer packages are installed"

log "\e[36m--------- Building completed ---------\e[39m"
